name: "Example 02"

# SiteInfo
site:
  data:
    lat: 35.2018863
    lon: -101.945027
    elev: 1099
    year: 2012
    tz: -6
    site_boundaries:
      verts:
        - [3.06, 288.87]
        - [0.0, 1084.03]
        - [1784.05, 1084.24]
        - [1794.09, 999.64]
        - [1494.34, 950.97]
        - [712.64, 262.8]
        - [1216.98, 272.36]
        - [1217.76, 151.62]
        - [708.14, 0.0]
    urdb_label: "5ca4d1175457a39b23b3d45e"
  hub_height: 97.0
  solar_resource_file: "resource_files/solar/35.2018863_-101.945027_psmv3_60_2012.csv"
  wind_resource_file: "resource_files/wind/35.2018863_-101.945027_windtoolkit_2012_60min_80m_100m.srw"
  grid_resource_file: "resource_files/grid/pricing-data-2015-IronMtn-002_factors.csv"
  solar: true
  wind: true
  wave: false

# Technologies
technologies:
  pv:
    system_capacity_kw: 464000
    dc_degradation: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    inv_eff: 97.95
    fin_model: !include default_fin_config.yaml
  wind:
    num_turbines: 90
    turbine_rating_kw: 5000
    elec_eff_loss: 4.9
    fin_model: !include default_fin_config.yaml
  battery:
    system_capacity_kwh: 1800000
    system_capacity_kw: 450000
    availability_loss: 0.1186
    fin_model: !include default_fin_config.yaml
  grid:
    interconnect_kw: 1000000
    ppa_price: 0.04
    fin_model: !include default_fin_config.yaml

config:
  simulation_options:
    cache: false
    wind:
      skip_financial: false
  dispatch_options:
    battery_dispatch: load_following_heuristic #load_following_heuristic #heuristic
    solver: cbc
    n_look_ahead_periods: 48
    grid_charging: false
    pv_charging_only: false
    include_lifecycle_count: false
  cost_info: # using utility scale costs
    wind_installed_cost_mw: 1262283.5555555555 # 2024 ATB for land-based wind class 1 moderate case year 2030 in 2022 USD, LCOH=7.31118816
    # wind_installed_cost_mw: 1273608. # 2024 ATB for land-based wind class 1 moderate case year 2030 in 2022 USD, LCOH=7.32756422
    # wind_installed_cost_mw: 1681308. # 2024 ATB for land-based wind class 1 moderate case year 2030 in 2022 USD, LCOH=7.91713118
    solar_installed_cost_mw: 1043702.0 # 2024 ATB for utility pv moderate case year 2030 in 2022 USD
    storage_installed_cost_mwh: 245692.0 # based on 2024 ATB utility-scale capital cost for battery energy costs for year 2030 in 2022 USD
    storage_installed_cost_mw: 317384.0 # 2024 ATB moderate case for commercial-scale battery power capital costs year 2030 in 2022 USD
    wind_om_per_kw: 29.2638 # 2024 ATB for land-based wind class 1 moderate case year 2030
    pv_om_per_kw: 17.9907 # 2024 ATB for utility-scale pv moderate case year 2024 in 2022 USD
    battery_om_per_kw: 7.9346 # 2024 ATB for utility-scale battery storage moderate case year 2030 in 2022 USD - ~0.025*317
