name: "technology_config"
description: "This plant has wind feeding into an electrolyzer with optimization"

technologies:
  hopp:
    performance_model:
      model: "hopp"
      config: !include ../tech_inputs/hopp_config_wind_solar_battery.yaml
    cost_model:
      model: "hopp"
    financial_model:
      group: "profast"
  electrolyzer:
    performance_model:
      model: "eco_pem_electrolyzer_performance"
    cost_model:
      model: "eco_pem_electrolyzer_cost"
    financial_model:
      group: "profast"
    model_inputs:
      shared_parameters:
        rating: 600. # MW
        location: "onshore"
        electrolyzer_capex: 500.

      performance_parameters:
        sizing:
          resize_for_enduse: False
          size_for: 'BOL' #'BOL' (generous) or 'EOL' (conservative)
          hydrogen_dmd:
        cluster_rating_MW: 60
        pem_control_type: 'basic'
        eol_eff_percent_loss: 10 #eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000. #number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: True #include degradation
        turndown_ratio: 0.1 #turndown_ratio = minimum_cluster_power/cluster_rating_MW

      cost_parameters:
        cost_model: "singlitico2021" # "basic" is a basic cost model based on H2a and HFTO program record for PEM electrolysis. "singlitico2021" uses cost estimates from that paper

      financial_parameters:
        replacement_cost_percent: 0.1 # percent of capex - H2A default case