name: "technology_config"
description: "This plant has wind feeding into an electrolyzer with optimization"

technologies:
  hopp:
    performance_model:
      model: "hopp"
      config: !include ../tech_inputs/hopp_config_wind_solar_battery.yaml
    cost_model:
      model: "hopp"
    financial_model:
      group: "profast"
    model_inputs:
      cost_parameters:
        cost_year: 2022
  electrolyzer:
    financial_model:
      group: "profast"
    performance_model:
      model: "eco_pem_electrolyzer_performance"
    cost_model:
      model: "singlitico_electrolyzer_cost"
    model_inputs:
      shared_parameters:
        location: "onshore"
        electrolyzer_capex: 500 # $/kW overnight installed capital costs for a 1 MW system in 2022
      performance_parameters:
        sizing:
          resize_for_enduse: False
          size_for: 'BOL' #'BOL' (generous) or 'EOL' (conservative)
          hydrogen_dmd:
        cluster_rating_MW: 60
        n_clusters: 10
        pem_control_type: 'basic'
        eol_eff_percent_loss: 10 #eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000. #number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: True #include degradation
        turndown_ratio: 0.1 #turndown_ratio = minimum_cluster_power/cluster_rating_MW

      financial_parameters:
        replacement_cost_percent: 0.1 # percent of capex - H2A default case


